### ISSUE TITLE
Import doesn't work neither with .pdf nor .png files

### ISSUE THREAD

**Issue by mattbel10** [patrickjane/ut-passes#3]
I tryed several attempts to import a pass, but didn't succeed. From error log, there is nothing useful to find out the error, it only states "Pass open failed: []".

**Comment by patrickjane** [comment]
Thanks for the feedback. The app does not support importing PDF or PNG files. It only works with passes in .pkpass format (Apple PassKit).

**Comment by mattbel10** [comment]
Sorry maybe I didn't understand the purpose of this app in the very first place. However, maybe it's just because I'm not familiar with .pkpass format, something I don't understand: I only own a UT device, never owned an Apple device and never I will. So, what a user like me would care about a format released by Apple? How can I use a pass to be shown in your app, exclusively for Ubuntu Touch devices? Is this format possible to be generated somehow? Thank you for your understanding and for your great job with this. Matteo

**Comment by patrickjane** [comment]
Well, the thing is, that most ticket providers (airlines, cinemas, ...) provide passes for their uses in .pkpass format. This allows users with iPhone devices to add the passes to their wallet app. Actually, most providers provide the tickets as .pkpass for iPhone as well as some other format for Android wallet.

So while this format is released by Apple, it is widely used. With this app, you can add those kind of passes to your UT device. For example, if you book a flight, the airline will usually provide a download link to a .pkpass file for the boarding pass, usually labeled with something like "Add to iOS wallet". You can then download this file and add it to the Passes app.

More info:
- https://passkit.com/
- https://en.wikipedia.org/wiki/Apple_Wallet
 
Hope this helps.

**Comment by mattbel10** [comment]
Thanks for your kind explanation. Now it's all understood. Will follow further development of this app ;) Cheers. Matteo
