### ISSUE TITLE
Problem with long strings

### ISSUE THREAD

**Issue by j2g2rp** [patrickjane/ut-passes#6]
Hi. Thanks again for this app.

On spanish translation some strings are longer than on english that causes that some strings doesn't fit correctly like on the image:
![screenshot20220121_230928179](https://user-images.githubusercontent.com/28528967/151028526-527ef53f-eeb9-4b54-9384-66edfc5679a0.png)
I don't know if some wrapping text mode could solve this problems...

**Comment by patrickjane** [comment]
Hey, thanks for the feedback. I can add word wrapping, but if possible I would like to avoid it. Maybe we can make the text shorter? E.g. something like "Actualizar los pases al iniciar la aplication"?

Let me check how it looks with word wrapping enabled. Maybe it doesn't look that bad.

**Comment by j2g2rp** [comment]
Ok @patrickjane let me know the results and if it doesn't looks fine I'll try to change the translation ;-)

**Comment by patrickjane** [comment]
Okay I think its okay with word wrap mode. I have just published an update. Can you install it and check if it works well for you?

**Comment by j2g2rp** [comment]
Looks great. Great job @patrickjane  :-D 10000thanks
![imagen](https://user-images.githubusercontent.com/28528967/151058381-444c18b3-2af2-4fce-9b6d-c7de20a9ca78.png)
