### ISSUE TITLE
Marking Passes as expired wrongfully

### ISSUE THREAD

**Issue by Tafitson** [patrickjane/ut-passes#7]
A pass with "expirationDate":"2022-05-03T18:45+02:00" is marked as expired in UT Passes, which it clearly should not be at May 1st.

**Comment by patrickjane** [comment]
Oh yeah. It seems like:

```
         if (QDateTime::currentDateTime().secsTo(dt) <= 0)
            pass->standard.expired = true;
         else
            pass->standard.expired = true;
```

.. just is not correct in any way. Will push an update fixing this.

**Comment by patrickjane** [comment]
@Tafitson please update to version 1.2.3 and check the expiration of your pass.

**Comment by Tafitson** [comment]
Uhh this was fast. Seems to work perfectly fine now, thanks a lot.

**Comment by patrickjane** [comment]
Thanks for testing.
