### ISSUE TITLE
Port to focal (20.04)

### ISSUE THREAD

**Issue by JamiKettunen** [patrickjane/ut-passes#9]
It would be great to have https://open-store.io/app/passes.s710 available for the upcoming Ubuntu Touch 20.04 release :)

**Comment by patrickjane** [comment]
I have published an updated version of the app on the focal channel. However, I do not have any device which is running focal at the moment, so I am unable to test. I would be happy if you could provide some feedback on whether or not the app is working well.

**Comment by JamiKettunen** [comment]
Hey! Sorry for the delay, the app launches just fine and testing with https://github.com/keefmoon/Passbook-Example-Code/blob/master/Pass-Example-Generic/Pass-Example-Generic.pkpass it seems to load just fine.

Unfortunately I don't have any other `.pkpass` files for testing at hand currently but seems to work well enough for now, so closing the issue :)
